### PR TITLE
Boost-histogram example

### PR DESCRIPTION
**Pull request by henryiii**
This:

* Sets up a new Jupyterbook site using the new beta version of Jupyter-book, which is simply fantastic.
* Adds a tutorial over converting histograms to ROOT and back, using both ROOT and uproot. Original content from @LovelyBuggies in https://github.com/scikit-hep/boost-histogram/pull/357.

I'd like to merge soon just to see if I can get the CI right (and it might be easier to review if we can view the final page) - we are not publishing this anywhere yet, so I don't think it hurts to experiment.

No page structure, etc really yet, I think that should come later. Will add a warning that the page URL may change.

PS: I think scikit-hep-tutorials should have tutorials that cover multiple packages or a package that has no docs of it's own. Larger packages should keep their own tutorials as well, though they should be linked to from these pages.

### CODE REVIEW

**Comment by LovelyBuggies** [comment]
@henryiii The ipynb file doesn't have output yet, am I expected to run it? And should we `import ROOT` here?

**Comment by henryiii** [comment]
Here we can import ROOT, and I'm hoping to get a green light for merging soon. You can wait to see it till then if you prefer.

**Comment by henryiii** [comment]
Todo for me: put the correct logo in

**Comment by henryiii** [comment]
If it helps, here's the latexed PDF (not generated currently in CI) (there's also a html-based one, I thought the latex one looked better), since the new Jupyter-book is based on Sphinx and therefore supports this sort of thing:

[book.pdf](https://github.com/scikit-hep/scikit-hep-tutorials/files/4665763/book.pdf)

**Comment by eduardo-rodrigues** [comment]
That's a neat idea, @henryiii,to have a Jupyter-book. My only request would be that we continue to make it easy for people to pick up the notebooks they like and play with them, "standalone", e.g. via Binder. This seems guaranteed here since all notebooks will simply be in a directory, and I guess we can have a bit of structure in there, to "help the eye".

> PS: I think scikit-hep-tutorials should have tutorials that cover multiple packages or a package that has no docs of it's own. Larger packages should keep their own tutorials as well, though they should be linked to from these pages.

Yes, totally. This we had agreed on already a while back, see https://github.com/scikit-hep/scikit-hep-tutorials/issues/2.

**Comment by eduardo-rodrigues** [comment]
Let me add @HDembinski and @mayou36 who have been active I discussions in this package.

**Review by eduardo-rodrigues — APPROVED** [review]
The notebook probably needs to be fine-tuned a bit, but the main purpose of this PR is to set up the Jupyter-book, hence I agree with you that a proper review of this short notebook can be done later.

As an example of what I really would like to see in the notebooks, see my intro to the notebook on `hepunits`, https://github.com/scikit-hep/scikit-hep-tutorials/pull/4, where at the top I put info on what the notebook is about, the Scikit-HEP packages used, and a list of authors to provide a sense of maintenance:

```
...
Or, an intro to the hepunits package while performing some time-of-flight studies.
Scikit-HEP packages used:
hepunits
Particle
Author: Eduardo Rodrigues
```

**Comment by henryiii** [comment]
If the binder link is not active yet, I'll make sure it gets turned on soon. Jupyter-book has built-in support for binder (since the notebooks are really just normal notebooks with a smidgeon of optional tags and markdown). I'll add the beginning, and also merge your HepUnits PR and see how they look together. We need to have some sort of folder structure; that's why I have the "URL  may change" warning because I'm not trying to solve that.

**Comment by henryiii** [comment]
> Scikit-HEP packages used:
> hepunits
> Particle

Why not just add a `# Scikit-HEP Packages` over the import statements from Scikit-HEP? Besides being a bit nicer to keep things organized for user imports, it also keeps from duplicating this as an import and as a list.

**Comment by eduardo-rodrigues** [comment]
See what I meant at https://nbviewer.jupyter.org/github/scikit-hep/scikit-hep-tutorials/blob/eduardo-units-tuto/basics/units.ipynb. It was an attempt to make it immediately clear what packages are discussed in the tutorial. Having # comments down the notebook is a different matter, and not as clear - if I understand what you mean.

Anyway, we have time to iterate and fine-tune. As usual it is easier to base discussions on concrete matters.

**Comment by henryiii** [comment]
I don't think GitHub is done with the issues, but this finally went through! Here's the link: https://scikit-hep.org/scikit-hep-tutorials (I wasn't expecting the scikit-hep.org prefix, but hey, very nice!)

**Comment by eduardo-rodrigues** [comment]
Cool!

**Pull request merged**
