### PR TITLE
Use scikit-hep metapackage in environment.yml

### LINKED ISSUE #6: environment.yaml for tutorials
As @henryiii said:

> There is a scikit-hep meta package for PyPI (not available on conda-forge yet). Also, if you use the same version of the same package in multiple conda environments, conda shares the packages for you - you only have one copy and then have links. But I do think we could have a recommended “environment.yml” that we could provide in the tutorial repo.

I think we could make an `environment.yaml` for the tutorials to build up the test environment.

Possible Reference:
- @eduardo-rodrigues's https://github.com/eduardo-rodrigues/2020-03-04_DESY_Scikit-HEP_HandsOn
- @LovelyBuggies's https://nino-hist.site/en/latest/user-guide/integration.html

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Closes https://github.com/scikit-hep/scikit-hep-tutorials/issues/6.

### CODE REVIEW

**Comment by henryiii** [comment]
No, these things should always come from Conda if possible. The conda version of awkward and boost-histogram are custom compiled for the platform you are on (and are the only way to get these things on Apple Silicon right now, I believe). You should use pip as little as possible, ideally not at all.

**Comment by henryiii** [comment]
I think if you manually include the needed conda packages, and then include scikit-hep from pip, then it can tell you have the correct versions of the other packages and will not install the PyPI versions (unless the versions are too tight and mismatched).

(A scikit-hep-feedstock on conda forge might not be a ridiculous idea...)

**Comment by eduardo-rodrigues** [comment]
Thanks for your comments, @henryiii.

> No, these things should always come from Conda if possible. The conda version of awkward and boost-histogram are custom compiled for the platform you are on (and are the only way to get these things on Apple Silicon right now, I believe). You should use pip as little as possible, ideally not at all.

No discussion there, certainly for "proper work". But do we really care about the custom compilation / greatest performance tuning to run a tutorial that is to be displayed in a book ;-). I'm just trying to simplify the settings here, but see below ..

> I think if you manually include the needed conda packages, and then include scikit-hep from pip, then it can tell you have the correct versions of the other packages and will not install the PyPI versions (unless the versions are too tight and mismatched).

I can certainly try that.

> (A scikit-hep-feedstock on conda forge might not be a ridiculous idea...)

Indeed I think it *is* a good idea in order to fully profit from the metapackage idea. We will have to get several of our org packages in conda, though, and that's going to take a bit of time. I've just created https://github.com/scikit-hep/scikit-hep/issues/131 to follow-up on this.

**Comment by eduardo-rodrigues** [comment]
Getting back to this - for reference the `scikit-hep` metapackage is available in Conda for the most recent versions. We can proceed with this MR.

**Comment by eduardo-rodrigues** [comment]
OK @henryiii, updated this MR to get pretty much everything from Conda. Ready for review :-).

**Review by henryiii — APPROVED** [review]
LGTM!

**Pull request merged**
